* Usage Example
This is an example implementation of a simple IRC echo bot using this IRC client framework.
Before you read this, you must read and understand the [[./guide.org][User's Guide]] and the [[./reference.org][Reference Manual]].

To implement the bot we must first create its handler function:

*** Handler
In a file called ~irc_dispatcher.erl~ add the following code:

#+BEGIN_SRC erlang
  -module(irc_dispatcher).

  -export([message/2]).


  message(Id, Message) ->
      case irc_parser:get_command(Message) of
          <<"PRIVMSG">> ->
              %% Extract the source of the message and the text
              {ok, Recv, Text} = irc_parser:privmsg(Message),
              %% Send the same message back
              irc_send:schedule(Id, irc_make:privmsg(Id, Recv, Text));
          _Command ->
              %% Ignore any other command
              void
      end.
#+END_SRC

Our handler function ~message/2~ takes two arguements: the client Id and the Message itself.

We extract the IRC command from the Message and check to see if it a PRIVMSG (a normal text
message sent to an IRC channel or privately with the bot).  If it is indeed a PRIVMSG we
send the same message back, otherwise we ignore the message.

Later we will configure ~message/2~ to be our handler function.

** Putting it all together

You can now compile the file above and run it together with the irc application.

Once you are in the Erlang emulator with the irc application started
and the module above loaded you can configure and start the IRC client with:

#+BEGIN_SRC erlang
  irc_config:set(example_id, #{address       => "irc.example.org",
                               port          => 6697,
                               tls           => true,
                               nickname      => "my_irc_client",
                               user          => "my_irc_client",
                               realname      => "My IRC client",
                               channels      => #{"#channel" => <<>>},
                               handler       => fun irc_dispatcher:message/2}.
  irc:connect(example_id).
#+END_SRC
